runtime: nodejs
env: flex
automatic_scaling:
    min_num_instances: 1
    max_num_instances: 10
    cool_down_period_sec: 180
    cpu_utilization:
        target_utilization: 0.95
resources:
    cpu: 1
    memory_gb: 1
    disk_size_gb: 10
readiness_check:
  app_start_timeout_sec: 1800